OgrenciTakip/Models/ErrorViewModel.cs
namespace OgrenciTakip.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

OgrenciTakip/Models/OgrenciModel.cs
namespace OgrenciTakip.Models
{
    public class OgrenciModel
    {
        public int OkulNo { get; set; }
        public string? Isim { get; set; }
        public string? SoyIsim { get; set; }
        public string? Sinifi { get; set; }
    }
}

OgrenciTakip/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OgrenciTakip.Models;
using System.Diagnostics;

namespace OgrenciTakip.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OgrenciTakip/Controllers/OgrenciController.cs
using Microsoft.AspNetCore.Mvc;
using OgrenciTakip.Models;
using System.Security.Cryptography;

namespace OgrenciTakip.Controllers
{
    public class OgrenciController : Controller
    {
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        static List<OgrenciModel> ogrenciler = new List<OgrenciModel>();

        [HttpGet]
        public IActionResult Kayit(OgrenciModel ogrenci)
        {
           ogrenciler.Add(ogrenci);
            if (ogrenci.OkulNo < 1)
            {
                return Content("Öğrenci Numarası Geçerli Değil");
            }
            else if (string.IsNullOrEmpty(ogrenci.Isim))
            {
                return Content("Öğrenci Adi Geçerli Değil");
            }
            else if(string.IsNullOrEmpty(ogrenci.SoyIsim))
            {
                return Content("Öğrenci Soyadı Geçerli Değil");
            }
            else if(string.IsNullOrEmpty (ogrenci.Sinifi))
            {
                return Content("Sinifiniz Geçerli Değil");
            }
            else
            {
                return Content("Öğrenci Kayıdı Başarılıdır");
            }
        }
        public IActionResult Listele(OgrenciModel ogrenci)
        {
            return View(ogrenciler);
        }

    }
}

OgrenciTakip/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

OgrenciTakip/Views/Ogrenci/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<form method="GET" action="/Ogrenci/Kayit">
    <div class="form-group">
        <label>Okul No</label>
        <input type="text" name="OkulNo" class="form-control" />
    </div>
    <div class="form-group">
        <label>Ad</label>
        <input type="text" name="Isim" class="form-control" />
    </div>
    <div class="form-group">
        <label>Soyad</label>
        <input type="text" name="SoyIsim" class="form-control" />
    </div>
    <div class="form-group">
        <label>Sınıf</label>
        <input type="text" name="Sinifi" class="form-control" />
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-outline-primary">Ekle</button>
        <button type="reset" class="btn btn-outline-danger">Sil</button>
    </div>
</form>

OgrenciTakip/Views/Ogrenci/Listele.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<OgrenciModel>

<table class="table">
    <thead>
        <tr>
            <th scope="col">Okul No</th>
            <th scope="col">İsim</th>
            <th scope="col">Soyisim</th>
            <th scope="col">Sınıfı</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var talebe in Model)
        {
            <tr>
                <th scope="row">@talebe.OkulNo</th>
                <td>@talebe.Isim</td>
                <td>@talebe.SoyIsim</td>
                <td>@talebe.Sinifi</td>
            </tr>
        }
    </tbody>
</table>

OgrenciTakip/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OgrenciTakip</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OgrenciTakip.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Öğrenci Takip</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Ana Sayfa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ogrenci" asp-action="Listele">Öğrenci Listele</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ogrenci" asp-action="Index">Öğrenci Kayit</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - OgrenciTakip - <a asp-area="" asp-controller="Home" asp-action="Privacy">Kaç</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>